name: MLOps Pipeline Automation

on: [push]

jobs:

  data_setup_and_eda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert numpy pandas tensorflow scikit-learn matplotlib
      - name: Execute data setup & EDA notebook
        run: |
          jupyter nbconvert --to notebook --execute dataSetup-EDA.ipynb --ExecutePreprocessor.timeout=1800 --output executed_dataSetup_and_EDA.ipynb

  feature_engineering:
    needs: data_setup_and_eda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert numpy pandas tensorflow scikit-learn shap matplotlib
      - name: Execute Feature Engineering notebook
        run: |
          jupyter nbconvert --to notebook --execute feature_engineering.ipynb --ExecutePreprocessor.timeout=1800 --output executed_feature_engineering.ipynb

  automl:
    needs: feature_engineering
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert numpy pandas tensorflow scikit-learn h2o optuna
      - name: Execute AutoML notebook
        run: |
          jupyter nbconvert --to notebook --execute automl.ipynb --ExecutePreprocessor.timeout=2400 --output executed_automl.ipynb

  monitoring:
    needs: automl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert numpy pandas tensorflow scikit-learn mlflow
      - name: Execute Monitoring notebook
        run: |
          jupyter nbconvert --to notebook --execute monitoring.ipynb --ExecutePreprocessor.timeout=1800 --output executed_monitoring.ipynb
